"""
Framework Templates - Code templates for different frameworks
"""
from typing import Dict, List
from pathlib import Path


class FrameworkTemplateGenerator:
    """Base class for framework-specific template generators"""
    
    def __init__(self, framework_id: str):
        self.framework_id = framework_id
    
    def generate_project_structure(self, project_name: str, entities: List[Dict]) -> Dict[str, str]:
        """Generate complete project structure"""
        raise NotImplementedError
    
    def generate_model(self, entity: Dict) -> str:
        """Generate model/entity class"""
        raise NotImplementedError
    
    def generate_route(self, entity: Dict) -> str:
        """Generate route/controller"""
        raise NotImplementedError
    
    def generate_config(self, project_name: str, config: Dict) -> Dict[str, str]:
        """Generate configuration files"""
        raise NotImplementedError


class NextJSTemplateGenerator(FrameworkTemplateGenerator):
    """Next.js template generator"""
    
    def __init__(self):
        super().__init__("nextjs")
    
    def generate_project_structure(self, project_name: str, entities: List[Dict]) -> Dict[str, str]:
        files = {}
        
        # package.json
        files["package.json"] = self._generate_package_json(project_name)
        
        # tsconfig.json
        files["tsconfig.json"] = self._generate_tsconfig()
        
        # next.config.js
        files["next.config.js"] = self._generate_next_config()
        
        # app/layout.tsx
        files["app/layout.tsx"] = self._generate_root_layout()
        
        # app/page.tsx
        files["app/page.tsx"] = self._generate_home_page()
        
        # app/api/route.ts (example API route)
        files["app/api/hello/route.ts"] = self._generate_api_route_example()
        
        # Generate entity pages
        for entity in entities:
            entity_name = entity["name"].lower()
            files[f"app/{entity_name}/page.tsx"] = self._generate_entity_page(entity)
            files[f"app/{entity_name}/[id]/page.tsx"] = self._generate_entity_detail_page(entity)
        
        # lib/types.ts
        files["lib/types.ts"] = self._generate_types(entities)
        
        # lib/api.ts
        files["lib/api.ts"] = self._generate_api_client()
        
        return files
    
    def _generate_package_json(self, project_name: str) -> str:
        return f'''{{
  "name": "{project_name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "next": "14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "axios": "^1.6.0"
  }},
  "devDependencies": {{
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0"
  }}
}}'''
    
    def _generate_tsconfig(self) -> str:
        return '''{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}'''
    
    def _generate_next_config(self) -> str:
        return '''/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig'''
    
    def _generate_root_layout(self) -> str:
        return '''import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by Autonomous App Builder',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}'''
    
    def _generate_home_page(self) -> str:
        return '''export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold mb-8">Welcome to Your App</h1>
      <p className="text-lg text-gray-600">Built with Next.js and TypeScript</p>
    </main>
  )
}'''
    
    def _generate_api_route_example(self) -> str:
        return '''import { NextResponse } from 'next/server'

export async function GET() {
  return NextResponse.json({ message: 'Hello from API' })
}'''
    
    def _generate_entity_page(self, entity: Dict) -> str:
        entity_name = entity["name"]
        return f'''import {{ Suspense }} from 'react'

export default function {entity_name}Page() {{
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">{entity_name} List</h1>
      <Suspense fallback={{<div>Loading...</div>}}>
        <{entity_name}List />
      </Suspense>
    </div>
  )
}}

function {entity_name}List() {{
  // Fetch and display {entity_name.lower()} here
  return <div>List of {entity_name.lower()}s</div>
}}'''
    
    def _generate_entity_detail_page(self, entity: Dict) -> str:
        entity_name = entity["name"]
        return f'''export default function {entity_name}DetailPage({{
  params
}}: {{
  params: {{ id: string }}
}}) {{
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">{entity_name} Details</h1>
      <p>ID: {{params.id}}</p>
    </div>
  )
}}'''
    
    def _generate_types(self, entities: List[Dict]) -> str:
        types = []
        for entity in entities:
            fields = entity.get("fields", [])
            field_defs = "\n  ".join([
                f"{field['name']}: {self._map_type_to_ts(field.get('type', 'string'))}"
                for field in fields
            ])
            types.append(f'''export interface {entity["name"]} {{
  id: string
  {field_defs}
  createdAt: string
  updatedAt: string
}}''')
        
        return "\n\n".join(types)
    
    def _map_type_to_ts(self, python_type: str) -> str:
        mapping = {
            "string": "string",
            "int": "number",
            "float": "number",
            "bool": "boolean",
            "datetime": "string",
            "list": "any[]",
            "dict": "Record<string, any>"
        }
        return mapping.get(python_type, "any")
    
    def _generate_api_client(self) -> str:
        return '''import axios from 'axios'

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'

const apiClient = axios.create({
  baseURL: API_URL,
  headers: {
    'Content-Type': 'application/json',
  },
})

// Add token to requests
apiClient.interceptors.request.use((config) => {
  const token = localStorage.getItem('token')
  if (token) {
    config.headers.Authorization = `Bearer ${token}`
  }
  return config
})

export default apiClient'''


class DjangoTemplateGenerator(FrameworkTemplateGenerator):
    """Django + DRF template generator"""
    
    def __init__(self):
        super().__init__("django")
    
    def generate_project_structure(self, project_name: str, entities: List[Dict]) -> Dict[str, str]:
        files = {}
        
        # requirements.txt
        files["requirements.txt"] = self._generate_requirements()
        
        # manage.py
        files["manage.py"] = self._generate_manage_py(project_name)
        
        # settings.py
        files[f"{project_name}/settings.py"] = self._generate_settings(project_name)
        
        # urls.py
        files[f"{project_name}/urls.py"] = self._generate_main_urls(project_name)
        
        # Create app for each entity
        for entity in entities:
            app_name = entity["name"].lower() + "s"
            files.update(self._generate_app_files(app_name, entity))
        
        return files
    
    def _generate_requirements(self) -> str:
        return '''Django==5.0.0
djangorestframework==3.14.0
django-cors-headers==4.3.0
psycopg2-binary==2.9.9
python-dotenv==1.0.0
djangorestframework-simplejwt==5.3.0'''
    
    def _generate_manage_py(self, project_name: str) -> str:
        return f'''#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys

def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', '{project_name}.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()'''
    
    def _generate_settings(self, project_name: str) -> str:
        return f'''from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.getenv('SECRET_KEY', 'your-secret-key-here')
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '{project_name}.urls'

TEMPLATES = [
    {{
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {{
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }},
    }},
]

DATABASES = {{
    'default': {{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', '{project_name}_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }}
}}

REST_FRAMEWORK = {{
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}}

CORS_ALLOW_ALL_ORIGINS = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
'''
    
    def _generate_main_urls(self, project_name: str) -> str:
        return '''from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view()),
    path('api/token/refresh/', TokenRefreshView.as_view()),
]'''
    
    def _generate_app_files(self, app_name: str, entity: Dict) -> Dict[str, str]:
        files = {}
        
        # models.py
        files[f"{app_name}/models.py"] = self._generate_model(entity)
        
        # serializers.py
        files[f"{app_name}/serializers.py"] = self._generate_serializers(entity)
        
        # views.py
        files[f"{app_name}/views.py"] = self._generate_views(entity)
        
        # urls.py
        files[f"{app_name}/urls.py"] = self._generate_app_urls(entity)
        
        # admin.py
        files[f"{app_name}/admin.py"] = self._generate_admin(entity)
        
        # __init__.py
        files[f"{app_name}/__init__.py"] = ""
        
        return files
    
    def generate_model(self, entity: Dict) -> str:
        return self._generate_model(entity)
    
    def _generate_model(self, entity: Dict) -> str:
        entity_name = entity["name"]
        fields = entity.get("fields", [])
        
        field_defs = []
        for field in fields:
            field_type = self._map_type_to_django(field.get("type", "string"))
            field_defs.append(f"    {field['name']} = models.{field_type}")
        
        fields_str = "\n".join(field_defs)
        
        return f'''from django.db import models

class {entity_name}(models.Model):
{fields_str}
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{entity_name} {{self.id}}"
'''
    
    def _map_type_to_django(self, field_type: str) -> str:
        mapping = {
            "string": "CharField(max_length=255)",
            "text": "TextField()",
            "int": "IntegerField()",
            "float": "FloatField()",
            "bool": "BooleanField(default=False)",
            "datetime": "DateTimeField()",
            "date": "DateField()",
            "email": "EmailField()",
            "url": "URLField()"
        }
        return mapping.get(field_type, "CharField(max_length=255)")
    
    def _generate_serializers(self, entity: Dict) -> str:
        entity_name = entity["name"]
        return f'''from rest_framework import serializers
from .models import {entity_name}

class {entity_name}Serializer(serializers.ModelSerializer):
    class Meta:
        model = {entity_name}
        fields = '__all__'
        read_only_fields = ['created_at', 'updated_at']
'''
    
    def _generate_views(self, entity: Dict) -> str:
        entity_name = entity["name"]
        return f'''from rest_framework import viewsets, permissions
from .models import {entity_name}
from .serializers import {entity_name}Serializer

class {entity_name}ViewSet(viewsets.ModelViewSet):
    queryset = {entity_name}.objects.all()
    serializer_class = {entity_name}Serializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
'''
    
    def _generate_app_urls(self, entity: Dict) -> str:
        entity_name = entity["name"]
        var_name = entity_name.lower()
        return f'''from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import {entity_name}ViewSet

router = DefaultRouter()
router.register(r'{var_name}s', {entity_name}ViewSet)

urlpatterns = [
    path('', include(router.urls)),
]
'''
    
    def _generate_admin(self, entity: Dict) -> str:
        entity_name = entity["name"]
        return f'''from django.contrib import admin
from .models import {entity_name}

@admin.register({entity_name})
class {entity_name}Admin(admin.ModelAdmin):
    list_display = ['id', 'created_at', 'updated_at']
    search_fields = ['id']
    ordering = ['-created_at']
'''


# Template generator factory
def get_template_generator(framework_id: str) -> FrameworkTemplateGenerator:
    """Get template generator for framework"""
    generators = {
        "nextjs": NextJSTemplateGenerator,
        "django": DjangoTemplateGenerator,
        # Add more as needed
    }
    
    generator_class = generators.get(framework_id)
    if generator_class:
        return generator_class()
    
    raise ValueError(f"No template generator found for framework: {framework_id}")
